# Generated by Django 2.1.5 on 2020-03-28 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('population', models.IntegerField(default=0)),
                ('infected', models.IntegerField(default=0)),
                ('dead', models.IntegerField(default=0)),
                ('cured', models.IntegerField(default=0)),
                ('dead_color', models.CharField(blank=True, max_length=7, null=True)),
                ('infected_color', models.CharField(blank=True, max_length=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subregion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('population', models.IntegerField(default=0)),
                ('infected', models.IntegerField(default=0)),
                ('dead', models.IntegerField(default=0)),
                ('cured', models.IntegerField(default=0)),
                ('dead_color', models.CharField(blank=True, max_length=7, null=True)),
                ('infected_color', models.CharField(blank=True, max_length=7, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Country')),
            ],
        ),
    ]
