# Generated by Django 2.1.5 on 2020-03-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='cases_per_million',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='country',
            name='critical',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='country',
            name='dead_per_million',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='country',
            name='new_dead',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='country',
            name='new_infected',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='country',
            name='total_cases',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subregion',
            name='total_cases',
            field=models.IntegerField(default=0),
        ),
    ]
