# Generated by Django 2.1.5 on 2020-03-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200328_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='first_case_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subregion',
            name='first_case_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
