# Generated by Django 2.1.5 on 2020-03-30 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20200328_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Afile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=10)),
                ('content', models.CharField(max_length=10)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
