# Generated by Django 2.1.5 on 2020-03-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_afile'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='percentage_increase',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subregion',
            name='percentage_increase',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
